
/*RESET*/
DROP ROLE MARTHA;
DROP ROLE USUARIO;
DROP ROLE FELIPE;

/*MARTHA INICIO A TRABAJAR EN LA EMPRESA HOY*/
CREATE ROLE MARTHA;
/*MARTHA TIENE CIERTAS FUNCIONES DENTRO DEL SISTEMA*/
GRANT EXECUTE ON PA_RH TO MARTHA;
/*SU PRIMERA TAREA FUE REGISTRAR UN NUEVO ASESOR QUE TAMBIEN INGRESABA ESE DIA*/
EXECUTE PA_RH.AD_ASESORES(1020659854, 3152205698, 'juan.manrique@profiler.com', 'Juan', 'Manrique', 'Calle 116 #48 29');
SELECT * FROM ASESORES;
/*MARTHA SE DIO CUENTA QUE HABIA PUESTO MAL EL NUMERO DE TELEFONO, ENTONCES DECIDE MODIFICARLO*/
EXECUTE PA_RH.MOD_ASESORES(4, 3108765421, 'juan.manrique@profiler.com', 'Juan', 'Manrique', 'Calle 116 #48 29');
SELECT * FROM ASESORES;

/*LLEGA UN USUARIO QUE DESEA REGISTRARSE EN LA PLATAFORMA COMO PERSONA NATURAL*/
CREATE ROLE USUARIO;
/*LE ASIGNAMOS LOS PERMISOS DE UNA PERSONA A EL USUARIO*/
GRANT EXECUTE ON PA_PERSONA TO USUARIO;
/*LO PRIMERO QUE HACE MARTHA ES REGISTRAR EL NUEVO USUARIO EN EL SISTEMA*/
EXECUTE PA_RH.AD_USUARIO('PN', 0001);
SELECT * FROM USUARIOS;
/*CUANDO SU JEFE VIO EL ASESOR QUE LE HABIA ASIGNADO, LE DIJO QUE LO CAMBIARA AL NUEVO QUE INGRESO PARA PROBARLO*/
EXECUTE PA_RH.MOD_USUARIO(6, 'PN', 4);
/*EL USUARIO DESEA REGISTRAR SUS PREFERENCIAS*/
EXECUTE PA_PERSONA.AD_PREFERENCIAS(6, 1500000, 'P', '<DIRECCION dato="CALLE 116 #54 -20"><DEPARTAMENTO dep = "BOGOTA"/><CITY Nombre="Bogota"><Localidad nombre="Usaquen"/><CodigoPostal codigo="110131"/></CITY></DIRECCION>', 'D');
/*EL USUARIO SIENTE QUE SE MENOSPRECIO Y QUIERE AUMENTAR SU SALARIO ESPERADO*/
SELECT * FROM PREFERENCIAS;
EXECUTE PA_PERSONA.MOD_PREFERENCIAS(6, 2500000, 'P', '<DIRECCION dato="CALLE 116 #54 -20"><DEPARTAMENTO dep = "BOGOTA"/><CITY Nombre="Bogota"><Localidad nombre="Usaquen"/><CodigoPostal codigo="110131"/></CITY></DIRECCION>', 'D');
/*EL USUARIO CREE QUE SE PUSO MUCHO, ENTONCES PREFIRIO ELIMINAR SUS PREFERENCIAS HASTA QUE SE DECIDA*/
EXECUTE PA_PERSONA.DEL_PREFERENCIAS(6);
/*EL USUARIO ENTONCES DECIDIO BUSCAR LAS FECHAS DE LAS CONVOCATORIAS PARA APLICAR A UNA*/
SELECT PA_PERSONA.CO_FECHAS_CONVOCATORIAS FROM DUAL;
/*Y ADEMAS QUISO BUSCAR LAS OFERTAS CON MAS DE DOS VACANTES PARA DECIRLE A UN AMIGO QUE TAMBIEN ESTA BUSCANDO TRABAJO*/
SELECT PA_PERSONA.CO_OFERTAS_VACANTES FROM DUAL;
/*EL USUARIO QUIERE CONFIRMAR CUALES OFERTAS ESTAN ABIERTAS PARA APLICAR, ASI QUE LE PIDE AYUDA A MARTHA*/
SELECT PA_RH.CO_OFERTAS_ABIERTAS(1) FROM DUAL;


/*FELIPE ES UN USUARIO QUE DESEA REGISTRARSE EN LA PLATAFORMA COMO EMPLEADOR*/
CREATE ROLE FELIPE;
/*SE LE ASIGNAN LOS PERMISOS PARA LOS EMPLEADORES*/
GRANT EXECUTE ON PA_EMPLEADOR TO FELIPE;
/*MARTHA YA TIENE EXPERIENCIA ASI QUE HACE EL PROCEDIMIENTO DE AGREGARLO AL SISTEMA*/
EXECUTE PA_RH.AD_USUARIO('E', 4);
/*FELIPE SIN PENSARLO, DECIDE CREAR UNA NUEVA OFERTA PARA UN USUARIO EN SU EMPRESA*/
EXECUTE PA_EMPLEADOR.AD_OFERTAS(7, 'Profesor o tutor de matematicas - Desarrollo de pruebas psicotecnicas', 'Empresa de desarrollo de software para seleccionar personal, requiere persona que tenga experiencia en cree, desarrolle, valide y entregue pruebas que evalúen aptitud matemática, razonamiento lógico, entre otras relacionadas con el área matemática.', 'VIVIR EN BOGOTA', 3, 'USAQUEN, BOGOTA', 2000000, 'P');
/*AHORA DECIDE ABRIR UNA CONVOCATORIA URGENTE*/
SELECT * FROM OFERTAS;
EXECUTE PA_EMPLEADOR.AD_CONVOCATORIAS(24, to_date('06 12 2020', 'DD MM YYYY'));
/*NUESTRO USUARIO SE DIO CUENTA DE LA CONVOCATORIA, Y DECIDIO ESTA VEZ COLOCAR SUS PREFERENCIAS CORRECTAS*/
EXECUTE PA_PERSONA.AD_PREFERENCIAS(6, 2000000, 'P', '<DIRECCION dato="CALLE 116 #54 -20"><DEPARTAMENTO dep = "BOGOTA"/><CITY Nombre="Bogota"><Localidad nombre="Usaquen"/><CodigoPostal codigo="110131"/></CITY></DIRECCION>', 'D');
/*COMO NO VIO RESULTADOS APLICADOS, ENTONCES DECIDIO BUSCAR LAS PERSONAS QUE CUMPLIERAN CON SUS REQUISITOS*/
SELECT PA_EMPLEADOR.CO_MODO_TRABAJO(1) FROM DUAL;
/*Y RESULTA QUE NUESTRO EMPLEADOR SE ENCONTRO A EL USUARIO, Y VIO QUE CUMPLIA CON LOS REQUISITOS ASI QUE DECIDIO CONTRATARLO*/
EXECUTE PA_EMPLEADOR.AD_CONTRATOS(25, 6, 'QUIERE TRABAJAR CON UN AMIGO', 1);

/*FIN.*/

