---OFERTAS
/*DATOS INCOMPLETOS*/
EXECUTE PC_OFERTAS.AD_OFERTAS(1, 'DESARROLLADOR FRONT', 'SE BUSCA DESARROLLADOR FRONT END CON CONOCIMIENTOS EN REACT JS', '+1 EXP', 2, 'BOGOTA, LA CANDELARIA', 2500000); 
/*DATOS QUE ROMPEN LAS REGLAS*/
EXECUTE PC_OFERTAS.MOD_OFERTAS(1, 'DESARROLLADOR FRONT REACT JS', 'SE BUSCA DESARROLLADOR FRONT END CON CONOCIMIENTOS EN REACT JS Y NODE JS', '+2 EXP', 2, 'BOGOTA, USAQUEN', 'R')
EXECUTE PC_OFERTAS.MOD_OFERTAS(-211, 'DESARROLLADOR FRONT REACT JS', 'SE BUSCA DESARROLLADOR FRONT END CON CONOCIMIENTOS EN REACT JS Y NODE JS', '+2 EXP', 2, 'BOGOTA, USAQUEN', 'REMOTO');
/*SIN ARGUMENTOS*/
EXECUTE PC_OFERTAS.DEL_OFERTAS();

---ASESORES
/*LLAVE PRIMARIA REPETIDA*/
EXECUTE PC_ASESORES.AD_ASESORES(123, 123456, 'JORGITO@GMAIL.COM', 'JORGITO', 'GUAYACO', 'CALLE 183 #10A');
/*ERROR EN EL TIPO DE DATOS*/
EXECUTE PC_ASESORES.MOD_ASESORES(5, 6543321, 'JORGITO@GMAIL.COM', JORGITO, 'GUAYACO', 'SUBA, FLORIDA');

---PREFERENCIAS
/*SALARIO MENOR AL ESPERADO*/
EXECUTE PC_PREFERENCIAS.AD_PREFERENCIAS(3, 500, 'P', '<DEPARTAMENTO dep = "Bogota"/><CITY Nombre="Bogota"><Localidad nombre="Usaquen"/><CodigoPostal codigo="110131"/></CITY></DIRECCION>', 'D');
/*CHECKS CORRUPTOS (REMO)*/
EXECUTE PC_PREFERENCIAS.MOD_PREFERENCIAS_USUARIO(2, 2500000, 'REMO', '<DEPARTAMENTO dep = "Bogota"/><CITY Nombre="Bogota"><Localidad nombre="Usaquen"/><CodigoPostal codigo="110131"/></CITY></DIRECCION>', 'N');

---CONTRATOS
/*OFERTA NO VALIDA*/
EXECUTE PC_CONTRATOS.AD_CONTRATOS(2, 100, 'TIENE DISLEXIA GRADO 3', 0);
/*VALORES ERRONEOS DENTRO DE LOS CHECKS*/
EXECUTE PC_CONTRATOS.MOD_CONTRATOS_CONTRATADO(2,1,500);

---CONVOCATORIAS
/*FORMATO DE FECHA INCORRECTO*/
EXECUTE PC_CONVOCATORIAS.AD_CONVOCATORIAS(2, '2016/25/36');

---USUARIOS
/*FUERA DE LAS REGLAS DECLARADAS*/
EXECUTE PC_USUARIOS.AD_USUARIO('PNa', 2);
/*CLAVE PRIMARIA NO NECESARIA*/
EXECUTE PC_USUARIOS.AD_USUARIO(4,'PN', 2);
