---OFERTAS
EXECUTE PC_OFERTAS.AD_OFERTAS(1, 'DESARROLLADOR FRONT', 'SE BUSCA DESARROLLADOR FRONT END CON CONOCIMIENTOS EN REACT JS', '+1 EXP', 2, 'BOGOTA, LA CANDELARIA', 2500000, 'R'); 
SELECT * FROM OFERTAS;
EXECUTE PC_OFERTAS.MOD_OFERTAS(1, 'DESARROLLADOR FRONT REACT JS', 'SE BUSCA DESARROLLADOR FRONT END CON CONOCIMIENTOS EN REACT JS Y NODE JS', '+2 EXP', 2, 'BOGOTA, USAQUEN', 'R')
EXECUTE PC_OFERTAS.DEL_OFERTAS(1);
SELECT PC_OFERTAS.CO_OFERTAS_VACANTES FROM DUAL;
SELECT PC_OFERTAS.CO_OFERTAS_ABIERTAS FROM DUAL;

---ASESORES
SELECT * FROM ASESORES;
/*revisar*/EXECUTE PC_ASESORES.AD_ASESORES(132459124, 123456, 'JORGITO@GMAIL.COM', 'JORGITO', 'GUAYACO', 'CALLE 183 #10A');
EXECUTE PC_ASESORES.MOD_ASESORES(5, 6543321, 'JORGITO@GMAIL.COM', 'JORGITO', 'GUAYACO', 'SUBA, FLORIDA');
EXECUTE PC_ASESORES.DEL_ASESORES(5);

---PREFERENCIAS
SELECT * FROM PREFERENCIAS;
EXECUTE PC_PREFERENCIAS.DEL_PREFERENCIAS(3);
EXECUTE PC_PREFERENCIAS.AD_PREFERENCIAS(3, 2000000, 'P', '<DIRECCION><DEPARTAMENTO dep = "Bogota"/><CITY Nombre="Bogota"><Localidad nombre="Usaquen"/><CodigoPostal codigo="110131"/></CITY></DIRECCION>', 'D');
EXECUTE PC_PREFERENCIAS.MOD_PREFERENCIAS_USUARIO(3, '2500000', 'R', '<DIRECCION><DEPARTAMENTO dep = "Bogota"/><CITY Nombre="Bogota"><Localidad nombre="Usaquen"/><CodigoPostal codigo="110131"/></CITY></DIRECCION>', 'N');
SELECT PC_PREFERENCIAS.CO_MODO_TRABAJO(1) FROM DUAL;

---CONTRATOS
SELECT * FROM CONTRATOS;
EXECUTE PC_CONTRATOS.AD_CONTRATOS(2, 1, 'TIENE DISLEXIA GRADO 3', 0);
EXECUTE PC_CONTRATOS.MOD_CONTRATOS_CONTRATADO(2,1,1);
SELECT PC_CONTRATOS.CO_DETALLES_CONTRATOS(1) FROM DUAL;
SELECT PC_CONTRATOS.CO_USUARIOS_CONTRATADOS(1) FROM DUAL;

---CONVOCATORIAS
SELECT * FROM CONVOCATORIAS;
SELECT * FROM OFERTAS;
EXECUTE PC_CONVOCATORIAS.AD_CONVOCATORIAS(2, CURRENT_DATE);
EXECUTE PC_CONVOCATORIAS.MOD_CONVOCATORIAS_FECHA_FIN(2, TO_DATE('12 06 2021', 'DD MM YYYY'));
EXECUTE PC_CONVOCATORIAS.DEL_CONVOCATORIAS(2);
SELECT PC_CONVOCATORIAS.CO_FECHAS_CONVOCATORIAS() FROM DUAL;
SELECT PC_CONVOCATORIAS.CO_OFERTAS_ABIERTAS(1) FROM DUAL;

---USUARIOS
SELECT * FROM USUARIOS;
EXECUTE PC_USUARIOS.AD_USUARIO('PN', 2);
EXECUTE PC_USUARIOS.MOD_USUARIO(4, 'E', 2);
EXECUTE PC_USUARIOS.DEL_USUARIO(6);
