CREATE OR REPLACE PACKAGE PA_PERSONA IS
    PROCEDURE AD_PREFERENCIAS (XUSUARIO IN NUMBER, XSALARIO_ESPERADO IN NUMBER, XMODO_TRABAJO IN VARCHAR2, XDIRECCION IN VARCHAR2, XJORNADA IN VARCHAR2);
    PROCEDURE MOD_PREFERENCIAS (XUSUARIO IN NUMBER, XSALARIO_ESPERADO IN NUMBER, XMODO_TRABAJO IN VARCHAR2, XDIRECCION IN VARCHAR2, XJORNADA IN VARCHAR2);
    PROCEDURE DEL_PREFERENCIAS (XUSUARIO IN NUMBER);
    /*CONSULTAS*/
    FUNCTION CO_FECHAS_CONVOCATORIAS RETURN SYS_REFCURSOR;
    FUNCTION CO_OFERTAS_VACANTES RETURN SYS_REFCURSOR;
END PA_PERSONA;
/
CREATE OR REPLACE PACKAGE PA_RH IS
    PROCEDURE AD_ASESORES (XIDENTIFICACION IN NUMBER, XCELULAR IN NUMBER, XCORREO IN VARCHAR2, XPRIMER_NOMBRE IN VARCHAR2, XPRIMER_APELLIDO IN VARCHAR2, XDIRECCION IN VARCHAR2);
    PROCEDURE AD_USUARIO (XTIPO_USUARIO IN VARCHAR2, XASESOR IN NUMBER);
    PROCEDURE MOD_USUARIO (XID IN NUMBER, XTIPO_USUARIO IN VARCHAR2, XASESOR IN NUMBER);
    PROCEDURE MOD_ASESORES (XCODIGO IN NUMBER, XCELULAR IN NUMBER, XCORREO IN VARCHAR2, XPRIMER_NOMBRE IN VARCHAR2, XPRIMER_APELLIDO IN VARCHAR2, XDIRECCION IN VARCHAR2);
    PROCEDURE DEL_USUARIO (XCODIGO IN NUMBER);
    PROCEDURE DEL_ASESORES (XCODIGO IN NUMBER);
    FUNCTION CO_USUARIOS_CONTRATADOS (XNUMERO IN NUMBER) RETURN SYS_REFCURSOR;
    FUNCTION CO_OFERTAS_ABIERTAS (XNUMERO IN NUMBER) RETURN SYS_REFCURSOR;
END PA_RH;
/
CREATE OR REPLACE PACKAGE PA_EMPLEADOR IS
    PROCEDURE AD_CONVOCATORIAS(XOFERTA IN NUMBER, XFECHA_FIN IN DATE);
    PROCEDURE AD_CONTRATOS (XUSUARIO IN NUMBER, XCONVOCATORIA IN NUMBER, XOBSERVACIONES IN VARCHAR2, XCONTRATADO IN NUMBER);
    PROCEDURE AD_OFERTAS (XCODIGO IN NUMBER, XTITULO IN VARCHAR2, XDESCRIPCION IN VARCHAR2, XREQUISITOS IN VARCHAR2, XVACANTES IN NUMBER, XUBICACION IN VARCHAR2, XSALARIO IN NUMBER, XMODO_TRABAJO IN VARCHAR2);
    PROCEDURE MOD_OFERTAS (XUSUARIO IN NUMBER, XTITULO IN VARCHAR2, XDESCRIPCION IN VARCHAR2, XREQUISITOS IN VARCHAR2, XVACANTES IN NUMBER, XUBICACION IN VARCHAR2, XMODO_TRABAJO IN VARCHAR2);
    PROCEDURE MOD_CONTRATOS_CONTRATADO (XUSUARIO IN NUMBER, XCONVOCATORIA IN NUMBER, XCONTRATADO IN NUMBER);
    PROCEDURE DEL_OFERTAS(XCODIGO IN NUMBER);
    FUNCTION CO_DETALLES_CONTRATOS(XNUMERO IN NUMBER) RETURN SYS_REFCURSOR;
    FUNCTION CO_MODO_TRABAJO (XNUMERO IN NUMBER) RETURN SYS_REFCURSOR;
END PA_EMPLEADOR;