--PERSONA
SELECT * FROM PREFERENCIAS;
EXECUTE PA_PERSONA.AD_PREFERENCIAS(5, 1500000, 'P', '<DIRECCION><DEPARTAMENTO dep = "Bogota"/><CITY Nombre="Bogota"><Localidad nombre="USME"/><CodigoPostal codigo="110131"/></CITY></DIRECCION>','D')
SELECT * FROM PREFERENCIAS;
EXECUTE PA_PERSONA.MOD_PREFERENCIAS(5, 1000000, 'SP', '<DIRECCION><DEPARTAMENTO dep = "Bogota"/><CITY Nombre="Bogota"><Localidad nombre="Usaquen"/><CodigoPostal codigo="110131"/></CITY></DIRECCION>', 'N')
SELECT * FROM PREFERENCIAS;
EXECUTE PA_PERSONA.DEL_PREFERENCIAS(5)
SELECT * FROM PREFERENCIAS;
SELECT PA_PERSONA.CO_FECHAS_CONVOCATORIAS FROM DUAL;
SELECT PA_PERSONA.CO_OFERTAS_VACANTES FROM DUAL;

--RH
SELECT * FROM ASESORES;
--EXECUTE PA_RH.AD_ASESORES(100, 3105555555, 'JORGITO@GMAIL.COM', 'JORGITO', 'GUAYACO', 'CALLE 183 NO 10A');
SELECT * FROM ASESORES;
SELECT * FROM USUARIOS;
EXECUTE PA_RH.AD_USUARIO('E','0001');
SELECT * FROM USUARIOS;
SELECT * FROM USUARIOS;
EXECUTE PA_RH.MOD_USUARIO(6, 'E', '0001');
SELECT * FROM USUARIOS;
SELECT * FROM ASESORES;
EXECUTE PA_RH.MOD_ASESORES(5, 6543321, 'JORGITO@GMAIL.COM', 'JORGITO', 'GUAYACO', 'SUBA, FLORIDA');
SELECT * FROM ASESORES;
SELECT * FROM USUARIOS;
EXECUTE PA_RH.DEL_USUARIO(6)
SELECT * FROM USUARIOS;
SELECT * FROM ASESORES;
EXECUTE PA_RH.DEL_ASESORES(4)
SELECT * FROM ASESORES;
SELECT PA_RH.CO_USUARIOS_CONTRATADOS(1) FROM DUAL;
SELECT PA_RH.CO_OFERTAS_ABIERTAS(1) FROM DUAL;

--EMPLEADOR
SELECT * FROM CONVOCATORIAS;
EXECUTE PA_EMPLEADOR.AD_CONVOCATORIAS(2, CURRENT_DATE);
SELECT * FROM CONVOCATORIAS;
SELECT * FROM CONTRATOS;
EXECUTE PA_EMPLEADOR.AD_CONTRATOS(2, 1, 'TIENE DISLEXIA GRADO 3', 0);
SELECT * FROM CONTRATOS;
EXECUTE PA_EMPLEADOR.MOD_CONTRATOS_CONTRATADO(2,1,1);
SELECT * FROM CONTRATOS;
SELECT * FROM OFERTAS;
EXECUTE PA_EMPLEADORS.AD_OFERTAS(1, 'DESARROLLADOR FRONT', 'SE BUSCA DESARROLLADOR FRONT END CON CONOCIMIENTOS EN REACT JS', '+1 EXP', 2, 'BOGOTA, LA CANDELARIA', 2500000, 'R'); 
SELECT * FROM OFERTAS;
EXECUTE PA_EMPLEADOR.MOD_OFERTAS(1, 'DESARROLLADOR FRONT REACT JS', 'SE BUSCA DESARROLLADOR FRONT END CON CONOCIMIENTOS EN REACT JS Y NODE JS', '+2 EXP', 2, 'BOGOTA, USAQUEN', 'R')
SELECT * FROM OFERTAS;
EXECUTE PA_EMPLEADOR.DEL_OFERTAS(1);
SELECT * FROM OFERTAS;
SELECT PA_EMPLEADOR.CO_MODO_TRABAJO(1) FROM DUAL;
SELECT PA_EMPLEADOR.CO_DETALLES_CONTRATOS(1) FROM DUAL;
