--SE BUSCA UNA OFERTA PARA CONTRATAR A DOS PERSONAS--
SELECT 
* 
FROM 
OFERTAS_VACANTES 
WHERE 
VACANTES > 2;

--SE NECESITAN CONOCER LAS CONVOCATORIAS QUE SE CIERRAN ANTES DEL 12 DE DICIEMBRE DEL 2020--
SELECT 
*
FROM
FECHAS_CONVOCATORIA
WHERE
FECHA_FIN < to_date('12 12 2020', 'DD MM YYYY');

--TITULO DE LAS OFERTAS CON CONVOCATORIAS ABIERTAS QUE CONTENGA LA PALABRA PROGRAMADORES--
SELECT 
TITULO 
FROM
OFERTAS_ABIERTAS
JOIN
OFERTAS
ON
OFERTAS_ABIERTAS.OFERTA = OFERTAS.CODIGO
WHERE TITULO LIKE ('%Programadores%');
--USUARIOS CON DISLEXIA--
SELECT
USUARIO
FROM
DETALLES_CONTRATOS
WHERE
OBSERVACIONES LIKE('%DISLEXIA%');
--USUARIOS CONTRATADOS--
SELECT * FROM USUARIOS_CONTRATADOS;
--USUARIOS QUE PREFIEREN EL MODO DE TRABAJO REMOTO--
SELECT * FROM PREFERENCIAS_USUARIOS_MODO_TRABAJO
WHERE MODO_TRABAJO = 'R';
