CREATE OR REPLACE VIEW OFERTAS_VACANTES AS(
    SELECT CODIGO,TITULO
    FROM
    OFERTAS
    WHERE
    VACANTES
    >
    1
);

SELECT * FROM OFERTAS_VACANTES;

CREATE OR REPLACE VIEW FECHAS_CONVOCATORIA AS(
    SELECT CODIGO,FECHA_INICIO,FECHA_FIN
    FROM CONVOCATORIAS
);

SELECT * FROM FECHAS_CONVOCATORIA;

CREATE OR REPLACE VIEW OFERTAS_ABIERTAS AS(
    SELECT CODIGO,OFERTA
    FROM CONVOCATORIAS
    WHERE
    FECHA_FIN > CURRENT_DATE
);

SELECT * FROM OFERTAS_ABIERTAS;

CREATE OR REPLACE VIEW DETALLES_CONTRATOS AS(
    SELECT USUARIO,OBSERVACIONES
    FROM CONTRATOS
);

SELECT * FROM DETALLES_CONTRATOS;

CREATE OR REPLACE VIEW USUARIOS_CONTRATADOS AS(
    SELECT USUARIO
    FROM
    CONTRATOS
    WHERE
    CONTRATADO = 1
);

SELECT * FROM USUARIOS_CONTRATADOS;

CREATE OR REPLACE VIEW PREFERENCIAS_USUARIOS_MODO_TRABAJO AS(
    SELECT USUARIO, MODO_TRABAJO
    FROM
    PREFERENCIAS
);

SELECT * FROM PREFERENCIAS_USUARIOS_MODO_TRABAJO;






