--VISTAS--
DROP VIEW OFERTAS_VACANTES;
DROP VIEW FECHAS_CONVOCATORIA;
DROP VIEW OFERTAS_ABIERTAS;
DROP VIEW DETALLES_CONTRATOS;
DROP VIEW USUARIOS_CONTRATADOS;
DROP VIEW PREFERENCIAS_USUARIOS_MODO_TRABAJO;
--INDICES--
DROP INDEX IASESORES;
DROP INDEX ICONVOCATORIAS;