ALTER TABLE USUARIOS ADD CONSTRAINT CK_USUARIOS_TIPO_USUARIO
  CHECK(TIPO_USUARIO IN ('E','PN'));
ALTER TABLE USUARIOS ADD CONSTRAINT CK_USUARIOS_CODIGO
  CHECK(ID > 0);
ALTER TABLE ASESORES ADD CONSTRAINT CK_ASESORES_IDENTIFICACION
  CHECK(IDENTIFICACION > 0);
ALTER TABLE ASESORES ADD CONSTRAINT CK_ASESORES_CELULAR
  CHECK(CELULAR > 0);
ALTER TABLE PREFERENCIAS ADD CONSTRAINT CK_REFERENCIAS_SALARIO
  CHECK(SALARIO_ESPERADO > 0);
ALTER TABLE OFERTAS ADD CONSTRAINT CK_OFERTAS_SALARIO
  CHECK(SALARIO > 0);
ALTER TABLE PREFERENCIAS ADD CONSTRAINT CK_PREFENCIAS_MODO_TRABAJO
  CHECK(MODO_TRABAJO IN('R','P','SP'));
ALTER TABLE PREFERENCIAS ADD CONSTRAINT CK_PREFERENCIAS_TIPO_JORNADA
  CHECK(JORNADA IN ('D', 'N'));
ALTER TABLE ASESORES ADD CONSTRAINT CK_ASESORES_MAIL
  CHECK(CORREO LIKE ('%@%.%'));
ALTER TABLE CONTRATOS ADD CONSTRAINT CK_CONTRATO_ESTADO
  CHECK(CONTRATADO IN (0,1,2,3)); 
ALTER TABLE OFERTAS ADD CONSTRAINT CK_OFERTAS_VACANTES
  CHECK(VACANTES >= 0);
ALTER TABLE ASESORES ADD CONSTRAINT CK_IDENTIFICACION_VALIDA
  CHECK(IDENTIFICACION > 0);
ALTER TABLE ASESORES ADD CONSTRAINT CK_CELULAR_VALIDO
  CHECK(CELULAR > 0 OR LENGTH(CELULAR) <= 11);