ALTER TABLE USUARIOS ADD CONSTRAINT FK_USUARIOS_ASESORES 
  FOREIGN KEY(ASESOR) REFERENCES ASESORES(CODIGO);
ALTER TABLE PREFERENCIAS ADD CONSTRAINT FK_PREFERENCIAS_USUARIOS 
  FOREIGN KEY(USUARIO) REFERENCES USUARIOS(ID);
ALTER TABLE OFERTAS ADD CONSTRAINT FK_OFERTAS_USUARIOS 
  FOREIGN KEY(USUARIO) REFERENCES USUARIOS(ID);
ALTER TABLE CONTRATOS ADD CONSTRAINT FK_CONTRATOS_USUARIOS 
  FOREIGN KEY(USUARIO) REFERENCES USUARIOS(ID);
ALTER TABLE CONTRATOS ADD CONSTRAINT FK_CONTRATOS_CONVOCATORIAS 
  FOREIGN KEY(CONVOCATORIA) REFERENCES CONVOCATORIAS(CODIGO);
ALTER TABLE CONVOCATORIAS ADD CONSTRAINT FK_CONVOCATORIAS_OFERTAS 
  FOREIGN KEY(OFERTA) REFERENCES OFERTAS(CODIGO);