ALTER TABLE USUARIOS ADD CONSTRAINT PK_USUARIO 
  PRIMARY KEY(ID);
ALTER TABLE PREFERENCIAS ADD CONSTRAINT PK_PREFERENCIAS 
  PRIMARY KEY(USUARIO);
ALTER TABLE ASESORES ADD CONSTRAINT PK_ASESORES 
  PRIMARY KEY(CODIGO);
ALTER TABLE CONVOCATORIAS ADD CONSTRAINT PK_CONVOCATORIAS 
  PRIMARY KEY(CODIGO);
ALTER TABLE CONTRATOS ADD CONSTRAINT PK_CONTRATOS 
  PRIMARY KEY(USUARIO, CONVOCATORIA);
ALTER TABLE OFERTAS ADD CONSTRAINT PK_OFERTAS 
  PRIMARY KEY(CODIGO);