CREATE TABLE USUARIOS(
	ID INTEGER NOT NULL, 
	TIPO_USUARIO VARCHAR2(2) NOT NULL, 
	ASESOR NUMBER(4)
);

CREATE TABLE PREFERENCIAS(
	USUARIO INTEGER NOT NULL, 
	SALARIO_ESPERADO NUMBER NOT NULL, 
	MODO_TRABAJO VARCHAR2(2) NOT NULL, 
	DIRECCION XMLTYPE NOT NULL, 
	JORNADA VARCHAR2(1)
);

CREATE TABLE ASESORES(
	CODIGO NUMBER(4) NOT NULL, 
	IDENTIFICACION NUMBER(10) NOT NULL, 
	CELULAR NUMBER(11), 
	CORREO VARCHAR2(30), 
	PRIMER_NOMBRE VARCHAR2(50) NOT NULL, 
	PRIMER_APELLIDO VARCHAR2(50) NOT NULL, 
	DIRECCION VARCHAR2(100) NOT NULL
);

CREATE TABLE OFERTAS(
	CODIGO INTEGER NOT NULL, 
	USUARIO INTEGER NOT NULL, 
	TITULO VARCHAR2(250) NOT NULL, 
	DESCRIPCION VARCHAR2(1000), 
	REQUISITOS VARCHAR2(500) NOT NULL, 
	VACANTES NUMBER(3) NOT NULL, 
	UBICACION VARCHAR2(100) NOT NULL, 
	SALARIO NUMBER NOT NULL, 
	MODO_TRABAJO VARCHAR2(1) NOT NULL
);

CREATE TABLE CONVOCATORIAS(
	CODIGO INTEGER NOT NULL, 
	OFERTA INTEGER NOT NULL, 
	FECHA_INICIO DATE NOT NULL, 
	FECHA_FIN DATE NOT NULL
);

CREATE TABLE CONTRATOS(
	USUARIO INTEGER NOT NULL, 
	CONVOCATORIA INTEGER NOT NULL, 
	OBSERVACIONES VARCHAR2(1000),
    CONTRATADO NUMBER(1)
);
