ALTER TABLE USUARIOS DROP CONSTRAINT FK_USUARIOS_ASESORES;
ALTER TABLE OFERTAS DROP CONSTRAINT FK_OFERTAS_USUARIOS;
ALTER TABLE CONTRATOS DROP CONSTRAINT FK_CONTRATOS_USUARIOS;
ALTER TABLE CONTRATOS DROP CONSTRAINT FK_CONTRATOS_CONVOCATORIAS;
ALTER TABLE CONVOCATORIAS DROP CONSTRAINT FK_CONVOCATORIAS_OFERTAS;
ALTER TABLE PREFERENCIAS DROP CONSTRAINT FK_PREFERENCIAS_USUARIOS;
ALTER TABLE USUARIOS ADD CONSTRAINT FK_USUARIOS_ASESORES
  FOREIGN KEY(ASESOR) REFERENCES ASESORES(CODIGO) ON DELETE SET NULL;
ALTER TABLE OFERTAS ADD CONSTRAINT FK_OFERTAS_USUARIOS 
  FOREIGN KEY(USUARIO) REFERENCES USUARIOS(ID) ON DELETE CASCADE;
ALTER TABLE CONTRATOS ADD CONSTRAINT FK_CONTRATOS_USUARIOS 
  FOREIGN KEY(USUARIO) REFERENCES USUARIOS(ID) ON DELETE CASCADE;
ALTER TABLE CONTRATOS ADD CONSTRAINT FK_CONTRATOS_CONVOCATORIAS 
  FOREIGN KEY(CONVOCATORIA) REFERENCES CONVOCATORIAS(CODIGO) ON DELETE CASCADE;
ALTER TABLE CONVOCATORIAS ADD CONSTRAINT FK_CONVOCATORIAS_OFERTAS 
  FOREIGN KEY(OFERTA) REFERENCES OFERTAS(CODIGO) ON DELETE CASCADE;
ALTER TABLE PREFERENCIAS ADD CONSTRAINT FK_PREFERENCIAS_USUARIOS 
  FOREIGN KEY(USUARIO) REFERENCES USUARIOS(ID) ON DELETE CASCADE;
