/*CONVOCATORIAS*/
/*LA FECHA DE INICIIO NO SE PUEDE MODIFICAR*/
UPDATE CONVOCATORIAS SET FECHA_INICIO = to_date('12 06 2021', 'DD MM YYYY');
/*EL CODIGO NO SE PUEDE MODIFICAR*/
UPDATE CONVOCATORIAS SET CODIGO = -1;

----------------OFERTAS-----------------
/*EL DATO DEL SALARIO NO SE PUEDE MODIFICAR*/
UPDATE OFERTAS SET SALARIO = 1234567;
/*EL CODIGO DE OFERTA NO SE PUEDE MODIFICAR*/
UPDATE OFERTAS SET CODIGO = -1;

----------------ASESORES----------------
/*EL CODIGO DEL ASESOR NO SE PUEDE MODIFICAR*/
UPDATE ASESORES SET CODIGO = -1;
/*EL NUMERO DE IDENTIFICACION DEL ASESOR NO SE PUEDE MODIFICAR*/
UPDATE ASESORES SET IDENTIFICACION = -1;

--ADICIONAR PREFERENCIA
/*El salario esperado no puede ser menor al salario minimo*/
INSERT INTO PREFERENCIAS VALUES(1, 1000, 'R', 'BOGOTA, USAQUEN', 'D');

----CONTRATOS----
/*EL UNICO DATO QUE SE PUEDE MODIFICAR ES CONTRATADO*/
UPDATE CONTRATOS SET USUARIO = -1;
/*LOS CONTRATOS NO SE PUEDEN ELIMINAR*/
DELETE FROM CONTRATOS WHERE USUARIO = 1;