----------------CONVOCATORIAS-----------------
/*LA FECHA Y EL CODIGO SE GENERAN AUTOMATICAMENTE*/
SELECT CODIGO,FECHA_INICIO FROM CONVOCATORIAS;
INSERT INTO CONVOCATORIAS VALUES(SEQ_CONVOCATORIAS.nextval,1,null,to_date('12 06 2021', 'DD MM YYYY'));
SELECT CODIGO,FECHA_INICIO FROM CONVOCATORIAS;

----------------OFERTAS-----------------
/*EL CODIGO DE OFERTA SE GENERA AUTOMATICAMENTE*/
SELECT CODIGO FROM OFERTAS;
INSERT INTO OFERTAS VALUES(SEQ_OFERTAS.nextval, 1, 'PRACTICAS PROFESIONALES', 'SE BUSCAN PRACTICANTES DE INGENIERIA DE SISTEMAS PARA TRABAJO EN BOGOTA', '+3 EXPERIENCIA' ,20, 'BOGOTA','897890','R');
SELECT CODIGO FROM OFERTAS;

----------------ASESORES----------------
/*EL CODIGO DEL ASESOR SE GENERA AUTOMATICAMENTE*/
SELECT CODIGO FROM ASESORES;
INSERT INTO ASESORES VALUES(SEQ_ASESORES.nextval,'1020310','123','123@GMAIL.COM','JUAN','COPETE','BOGOTA');
SELECT CODIGO FROM ASESORES;
/*SI NO SE INDICA LA DIRECCION, SE DEBE LLENAR EL CAMPO CON 'BOGOTA, COLOMBIA'*/
SELECT DIRECCION FROM ASESORES ORDER BY CODIGO DESC;
INSERT INTO ASESORES VALUES(SEQ_ASESORES.nextval,'856874','12123413','1221343@GMAIL.COM','JUAN','COPETE',null);
SELECT DIRECCION FROM ASESORES ORDER BY CODIGO DESC;
/*SI UN ASESOR SE ELIMINA, EL USUARIO QUE TENIA ASIGNADO ESE ASESOR, QUEDA CON UN VALOR NULL*/
SELECT * FROM USUARIOS;
DELETE FROM ASESORES WHERE CODIGO = 1;
SELECT * FROM USUARIOS;

--CONTRATOS---
/*SI UN CONTRATO NO TIENE OBSERVACIONES EL CAMPO SE LLENA CON 'SIN OBSERVACIONES'*/
SELECT * FROM CONTRATOS;
INSERT INTO CONTRATOS VALUES(1, 1, null, 1);
SELECT * FROM CONTRATOS;